# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171120_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('curso', models.IntegerField(choices=[(1, 'Agronegócio'), (2, 'Agronomia'), (3, 'Secretariado Executivo'), (4, 'Sistemas de Informação'), (5, 'Sistemas para Internet'), (6, 'Zootecnia')])),
                ('aluno', models.ManyToManyField(to='core.Aluno')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='avaliador',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='avaliador',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='avaliador',
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='Avaliador',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
