# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 17:27
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171130_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcc',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[core.validators.validate_file_extension]),
        ),
    ]
