# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tcc_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcc',
            name='cpf',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
