# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_aluno_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
    ]
